"""mews

Revision ID: c75659953a89
Revises: 58485a837404
Create Date: 2025-11-12 05:37:01.510904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75659953a89'
down_revision: Union[str, Sequence[str], None] = '58485a837404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_plans', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'scene_plans', 'scene_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scene_plans', type_='foreignkey')
    op.drop_column('scene_plans', 'group_id')
    # ### end Alembic commands ###
